name: fertility_boost
version: 1.11.1+5
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.2 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  responsive_sizer: ^3.2.0
  pin_code_fields: ^8.0.1
  google_nav_bar: ^5.0.6
  easy_date_timeline: ^1.0.2
  syncfusion_flutter_gauges: ^26.2.9
  http: ^1.1.0
  saver_gallery: ^3.0.3
  internet_connection_checker: ^1.0.0+1
  connectivity_plus: ^6.0.5
  shared_preferences: ^2.2.2
  scrollable_clean_calendar: ^1.4.1
  shimmer: ^3.0.0
  animated_rating_bar: ^0.0.8
  time_slot: ^1.0.0
  flutter_launcher_icons: ^0.13.1
  firebase_core: ^2.21.0
  cloud_firestore: ^4.12.2
  firebase_storage: ^11.4.1
  just_audio: ^0.9.35
  audio_video_progress_bar: ^2.0.1
  appinio_video_player: ^1.2.2
  image_cropper: ^5.0.0
  image_picker: ^1.0.4
  flutter_downloader: ^1.11.4
  flutter_media_downloader: ^1.0.2
  open_filex: ^4.3.4
  chewie: ^1.7.1
  video_player: ^2.8.6
  googleapis: ^13.1.0
  google_sign_in: ^6.2.1
  pedometer: ^4.0.1
  cupertino_stepper: ^0.2.1
  another_stepper: ^1.2.2
  table_calendar: ^3.0.9
  google_maps_flutter: ^2.5.0
  google_places_flutter_api: ^1.0.2
  geocoding: ^3.0.0
  intl: ^0.19.0
  calendar_view: ^1.0.4
  carousel_slider: ^4.2.1
  location: ^6.0.1
  video_thumbnail: ^0.5.3
  path_provider: ^2.1.1
  webview_flutter: ^4.7.0
  flutter_html: ^3.0.0-beta.2
  fl_chart: ^0.67.0
  cached_network_image: ^3.3.1
  url_launcher: ^6.2.3
# flutter_local_notifications: ^17.0.0
  sensors_plus: ^4.0.2
  flutter_local_notifications: ^16.3.2
  advance_pdf_viewer_fork: ^2.0.0
  #Graph drawing dependencies
  flutter_charts: ^0.5.2
  syncfusion_flutter_charts: ^26.2.9
  flutter_cached_pdfview: ^0.4.2
  mrx_charts: ^0.1.3
  file_picker: ^8.0.0
  logger: ^2.3.0
  flutter_facebook_auth: ^7.0.0
  firebase_messaging: ^14.9.4
  vimeo_player_flutter: ^0.1.0
  social_login_buttons: ^1.0.7
  firebase_auth: ^4.20.0



dev_dependencies: 
  flutter_lints: ^3.0.1
  flutter_test: 
    sdk: flutter

flutter_launcher_icons:
  image_path: "assets/images/img_screen_logo.png"

  android:
    adaptive_icon_background: "#FFFFFF"
    adaptive_icon_foreground: "assets/images/img_screen_logo.png"
    round_icon: true

  ios:
    image_path_ios: "assets/images/img_screen_logo.png"
    remove_alpha_ios: true
    precomposed: true

#flutter_launcher_icons:
#  android: "assets/images/img_screen_logo.png"
#  ios: true
#  image_path: "assets/images/img_screen_logo.png"
#  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/gif/
    - assets/faltu/

  fonts:
    - family: BeVietnamPro
      fonts:
        - asset: assets/fonts/BeVietnamPro-Light.ttf
          weight: 300
        - asset: assets/fonts/BeVietnamPro-Regular.ttf
          weight: 400
        - asset: assets/fonts/BeVietnamPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/BeVietnamPro-Bold.ttf
          weight: 700

